apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-inbound-ports: "8080"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: microservice-demo
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: ENVIRONMENT
              value: "development"
            - name: TRACING_ENABLED
              value: "true"
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3 