apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: microservice-demo-dev
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../base

namePrefix: ""
nameSuffix: "-dev"

commonLabels:
  environment: dev
  tier: development

commonAnnotations:
  environment: development
  deployment.strategy: "rolling"

replicas:
  - name: microservice-demo
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

configMapGenerator:
  - name: microservice-demo-config
    behavior: merge
    literals:
      - log-level=DEBUG
      - environment=development
      - tracing-enabled=true

images:
  - name: ghcr.io/user/microservice-demo
    newTag: dev 