apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-demo-config
  labels:
    app: microservice-demo
    component: config
data:
  # Application configuration
  log-level: "INFO"
  environment: "development"
  tracing-enabled: "false"
  
  # Server configuration
  server-host: "0.0.0.0"
  server-port: "8080"
  
  # Monitoring configuration
  metrics-enabled: "true"
  health-check-interval: "30"
  
  # Application metadata
  app-name: "microservice-demo"
  app-version: "1.0.0" 