apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: microservice-demo-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: microservice-demo
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: microservice-platform

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: "kustomize"

namePrefix: ""
nameSuffix: ""

images:
  - name: ghcr.io/user/microservice-demo
    newTag: latest 