apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-demo-monitor
  labels:
    app: microservice-demo
    component: monitoring
spec:
  selector:
    matchLabels:
      app: microservice-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - default

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: microservice-demo-alerts
  labels:
    app: microservice-demo
    component: monitoring
spec:
  groups:
    - name: microservice-demo.rules
      rules:
        - alert: MicroserviceDown
          expr: up{job="microservice-demo"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Microservice instance is down"
            description: "Microservice demo instance {{ $labels.instance }} has been down for more than 5 minutes."
        
        - alert: HighErrorRate
          expr: rate(http_requests_total{job="microservice-demo",status=~"5.."}[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High error rate detected"
            description: "Error rate is {{ $value }} errors per second for {{ $labels.instance }}."
        
        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes{pod=~"microservice-demo.*"} / container_spec_memory_limit_bytes > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage"
            description: "Memory usage is above 80% for {{ $labels.pod }}."
        
        - alert: HighCPUUsage
          expr: rate(container_cpu_usage_seconds_total{pod=~"microservice-demo.*"}[5m]) / container_spec_cpu_quota * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage"
            description: "CPU usage is above 80% for {{ $labels.pod }}." 