apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: microservice-demo
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENVIRONMENT
              value: "staging"
            - name: TRACING_ENABLED
              value: "true"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3 